# Generated by Django 5.1.7 on 2025-03-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tag_taskstatus_regulartask_tags_urgenttask_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgenttask',
            name='dependencies',
            field=models.ManyToManyField(blank=True, to='tasks.urgenttask'),
        ),
    ]
