# Generated by Django 5.1.7 on 2025-03-15 05:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_urgenttask_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tasks.urgenttask')),
            ],
        ),
        migrations.RemoveField(
            model_name='urgenttask',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='urgenttask',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.urgenttask'),
        ),
    ]
