# Generated by Django 5.1.7 on 2025-03-15 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_deadline_remove_urgenttask_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='urgenttask',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='urgenttask',
            index=models.Index(fields=['user', 'priority'], name='user_priority_idx'),
        ),
    ]
