# Generated by Django 5.1.7 on 2025-03-15 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_taskcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPriorityHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_priority', models.IntegerField(null=True)),
                ('new_priority', models.IntegerField()),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorities', to='tasks.urgenttask')),
            ],
            options={
                'indexes': [models.Index(fields=['task', 'changed_at'], name='tasks_taskp_task_id_15ad44_idx')],
            },
        ),
    ]
