# Generated by Django 5.1.7 on 2025-03-15 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taskpriorityhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskpriorityhistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_history', to='tasks.urgenttask'),
        ),
    ]
